apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  # der Port, an dem wir unseren Service erreichen wollen (z.B. 'test-app:80' für http)
  - port: {{ .Values.port }}
    # der auf dem der Docker-Container intern lauscht
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
